
package Cafe;

import javax.swing.JOptionPane;

public class book_rect_view extends javax.swing.JPanel {

    /**
     * Creates new form book_rect_view
     * @param book
     */
    Food book;
    public book_rect_view(Food book) {
        initComponents();
        this.book = book;
        lb_bookname.setText(book.Iname);
//        lb_author.setText(book.Icategory+" ");
        lb_genre.setText(book.Icategory);
//        lb_year.setText(String.valueOf(book.year));
        lb_genre.setText(String.valueOf(book.rating));
        lb_price.setText(String.valueOf(book.Iprice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_bookname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_genre = new javax.swing.JLabel();
        lb_price = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_rating = new javax.swing.JLabel();
        imglabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(280, 420));
        setPreferredSize(new java.awt.Dimension(280, 420));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_bookname.setFont(new java.awt.Font("Glass Antiqua", 1, 36)); // NOI18N
        lb_bookname.setForeground(new java.awt.Color(255, 255, 255));
        lb_bookname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bookname.setText("Book Name");
        add(lb_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 50));

        jLabel3.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 30));

        lb_genre.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        lb_genre.setForeground(new java.awt.Color(255, 255, 255));
        lb_genre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_genre.setText("Starter");
        add(lb_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, 20));

        lb_price.setBackground(new java.awt.Color(255, 255, 255));
        lb_price.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_price.setForeground(new java.awt.Color(255, 255, 255));
        lb_price.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_price.setText("250");
        add(lb_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 120, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 60, 30));

        jLabel7.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rating");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 30));

        lb_rating.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        lb_rating.setForeground(new java.awt.Color(255, 255, 255));
        lb_rating.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_rating.setText("4.2");
        add(lb_rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 120, 20));

        imglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG Panel.jpg"))); // NOI18N
        add(imglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 420));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imglabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_bookname;
    private javax.swing.JLabel lb_genre;
    private javax.swing.JLabel lb_price;
    private javax.swing.JLabel lb_rating;
    // End of variables declaration//GEN-END:variables
}
